### PR TITLE
Renaming `GITHUB_TOKEN` to `GH_TOKEN`

### PR DESCRIPTION
**Pull request by salilsub**
## Description

Per the [GitHub Actions docs](https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions#naming-your-secrets), secrets cannot be prefixed with `GITHUB_`. This change is amending `GITHUB_TOKEN` to `GH_TOKEN`, which does not violate these rules.

## Testing plan

1. Attempt to create a repository secret for Actions called `GITHUB_TOKEN`. An error will be thrown and the secret will not be created.
2. Attempt to create a repository secret for Actions called `GH_TOKEN`. It will be created properly
3. Update the example speculative plan on PR workflow to use `GH_TOKEN`.
4. Create a PR which has terraform changes, the comment with speculative run information and link to HCP Terraform will be included.
## External links

GitHub Actions [secrets docs](https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions#naming-your-secrets)

### CODE REVIEW

**Comment by paulanunda** [comment]
👋🏾👋🏾👋🏾 @salilsub

**Comment by mjyocca** [comment]
👋 😎  @salilsub

**Review by mjyocca — COMMENTED** [review]
Thanks for raising [this](https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions#naming-your-secrets)!

Please correct me if I'm wrong, but I think `GITHUB_TOKEN` is one [provided](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#about-the-github_token-secret) by GitHub automatically to authenticate the workflow. 

It looks like we could use `${{ github.token }}` [context](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context) instead which would make it easier to distinguish between GHA provided secrets and user defined secrets.

**Comment by zainq11** [comment]
👋 @salilsub

**Comment by aaabdelgany** [comment]
🤗 @salilsub

**Comment by salilsub** [comment]
@mjyocca I think I figured out the issue here. When I ran the workflow as-is, I got an error: 
`Error: Unhandled error: HttpError: Resource not accessible by integration`
Which I interpreted that I didn't have a valid token to write comments to the PR. However, it turns out that the issue was that the default for my repos was to use the restricted token (which had no permissions in Actions) rather than the permissive (which had the necessary read/write).
My interpretation of how to fix this was to try and create a new `GITHUB_TOKEN` secret and when I couldn't, I created `GH_TOKEN` instead. However I think the better solution is to update the permissions which is described [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#setting-the-permissions-of-the-github_token-for-your-repository).
I do think it makes sense to amend the README to point people in this direction. Unless you tell me otherwise, I'll close this PR and create a new one that updates the readme with a link to the above doc.

**Comment by mjyocca** [comment]
> @mjyocca I think I figured out the issue here. When I ran the workflow as-is, I got an error: `Error: Unhandled error: HttpError: Resource not accessible by integration` Which I interpreted that I didn't have a valid token to write comments to the PR. However, it turns out that the issue was that the default for my repos was to use the restricted token (which had no permissions in Actions) rather than the permissive (which had the necessary read/write). My interpretation of how to fix this was to try and create a new `GITHUB_TOKEN` secret and when I couldn't, I created `GH_TOKEN` instead. However I think the better solution is to update the permissions which is described [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#setting-the-permissions-of-the-github_token-for-your-repository). I do think it makes sense to amend the README to point people in this direction. Unless you tell me otherwise, I'll close this PR and create a new one that updates the readme with a link to the above doc.

Ahhhh that makes a lot of sense. Yeah I think that'd be great to add that to the README 👍. Maybe a small section linking to the permission docs commented out in the workflow file itself.

**Comment by salilsub** [comment]
I've made this changes in a new PR (https://github.com/hashicorp/tfc-workflows-github/pull/2976). Closing this one.

**Pull request closed without merging**
